apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-1-pod
  template:
    metadata:
      labels:
        app: api-1-pod
    spec:
      containers:
       - name: api-1-container
         image: asadis7171/api:node-1
         ports:
          - containerPort: 80