apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-2-pod
  template:
    metadata:
      labels:
        app: api-2-pod
    spec:
      containers:
       - name: api-2-container
         image: asadis7171/api:node-2
         ports:
          - containerPort: 80