apiVersion: v1
kind: Service
metadata:
  name: ha-proxy-service
spec:
  selector:
    app: haproxy-pod
  ports:
    - name: http
      protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 30009
    - name: http-alt
      protocol: "TCP"
      port: 8404
      targetPort: 8404
      nodePort: 30010
  type: NodePort