# Use the official HAProxy image as the base
FROM haproxy

# Copy the haproxy configuration file into the image
COPY ./haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg

# Expose the ports
EXPOSE 80 8080 8404
